Repository zenn-dev/zenn-editor, pull requests merged in 2021-06, with the labels that each got.

#153 setup GitHub Actions for canary version
  .github/workflows/publish-canary.yml
  .github/workflows/test.yml
  .github/workflows/validate-pr.yml
  README.md
  packages/zenn-cli/next.config.js
Labels: chore

#154 chore: Automatically versionup package.json when pr merged to canary
  .github/workflows/publish-canary.yml
Labels: chore

#155 ドキュメントとGitHub Actionsの調整
  .github/workflows/publish.yml
  .github/workflows/validate-pr.yml
  CONTRIBUTING.md
  DEVELOPMENT.md
Labels: chore

#156 Fix GitHub actions
  .github/workflows/publish.yml
  .github/workflows/validate-pr.yml
Labels: chore

#157 Github Actionsのエラーを解消
  .github/workflows/publish.yml
Labels: chore

#158 GitHub Actionsの効率化
  .github/workflows/publish.yml
Labels: chore

#159 GitHub Actionsのエラーを修正
  .github/workflows/publish.yml
Labels: chore

#160 GitHub Actionsのエラーを解消
  .github/workflows/publish.yml
Labels: chore

#161 GitHub Actionsでのlernaからのコミットが失敗する問題の解消
  .github/workflows/publish.yml
Labels: chore

#162 GitHub Actionsでのlernaのエラーを解消
  .github/workflows/publish.yml
Labels: chore

#163 GitHub Actionsからlernaコマンドが失敗する問題の解消
  .github/workflows/publish.yml
Labels: chore

#164 GitHub Actionsの誤りを修正
  .github/workflows/publish.yml
Labels: chore

#165 CLIの文言を調整
  packages/zenn-cli/cli/init.ts
Labels: chore

#166 GitHub Actionsからのリリース
  .github/release-drafter.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .github/workflows/validate-pr.yml
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  lerna.json
  packages/example/package.json
  packages/zenn-cli/cli/index.ts
  packages/zenn-cli/cli/init.ts
  packages/zenn-cli/next.config.js
  packages/zenn-cli/package.json
  packages/zenn-cli/pages/404.tsx
  packages/zenn-cli/pages/_error.tsx
  packages/zenn-cli/utils/api/books.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
Labels: release

#170 Update KaTeX version
  packages/zenn-embed-elements/src/classes/katex.ts
Labels: enhancement

#171 コメントの修正
  packages/zenn-embed-elements/src/classes/katex.ts
Labels: chore

#172 プルリクエストテンプレートの追加
  docs/CONTRIBUTING.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: chore

#173 ディレクトリの整理
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/publish.yml
  CONTRIBUTING.md
  docs/TEST.md
Labels: chore

#150 feat: mermaid.js 対応
  packages/example/articles/example.md
  packages/zenn-embed-elements/src/classes/mermaid.ts
  packages/zenn-embed-elements/src/index.ts
  packages/zenn-markdown-html/__tests__/mermaid.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/jest.config.js
  packages/zenn-markdown-html/src/index.ts
  packages/zenn-markdown-html/src/utils/md-mermaid.ts
Labels: feature

#174 KaTexのバージョンを一旦v0.12.0に固定
  .github/workflows/publish-canary.yml
  .github/workflows/publish-latest.yml
  packages/zenn-embed-elements/src/classes/katex.ts
Labels: fix

#175 release
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-latest.yml
  docs/TEST.md
  lerna.json
  packages/example/articles/example.md
  packages/example/package.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/lib/index.css
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-embed-elements/src/classes/katex.ts
  packages/zenn-embed-elements/src/classes/mermaid.ts
  packages/zenn-embed-elements/src/index.ts
  packages/zenn-markdown-html/__tests__/mermaid.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/jest.config.js
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/index.ts
  packages/zenn-markdown-html/src/utils/md-mermaid.ts
Labels: release

#179 node-sassをsassに入れ替え
  .github/workflows/publish-latest.yml
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: chore

#180 release: update dependencies
  .github/workflows/publish-latest.yml
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/index.html
  packages/zenn-content-css/.gitignore
  packages/zenn-content-css/lib/index.css
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#181 release: tiny fix
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-cli/vite.config.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-embed-elements/tsconfig.json
  packages/zenn-markdown-html/package.json
Labels: release

#182 KaTeX のバージョンを v0.12 から v0.13 へ更新
  packages/zenn-embed-elements/src/classes/katex.ts
Labels: chore

#184 release: upgrade KaTeX to v0.13
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-embed-elements/src/classes/katex.ts
  packages/zenn-markdown-html/package.json
Labels: release

#185 クライアントのindex.htmlがキャッシュされる問題の修正
  packages/zenn-cli/src/server/preview/app.ts
Labels: bugfix
