Repository zenn-dev/zenn-editor, pull requests merged in 2021-09, with the labels that each got.

#212 タイトル文字数のバリデーションをzenn.devと統一
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/__tests__/lib/validator.test.ts
  packages/zenn-cli/src/client/lib/validator.ts
  packages/zenn-cli/src/server/__tests__/commands/help.test.ts
  packages/zenn-cli/src/server/__tests__/commands/index.test.ts
  packages/zenn-cli/src/server/__tests__/commands/init.test.ts
  packages/zenn-cli/src/server/__tests__/commands/new-article.test.ts
  packages/zenn-cli/src/server/__tests__/commands/new-book.test.ts
  packages/zenn-cli/src/server/__tests__/commands/preview.test.ts
  packages/zenn-cli/src/server/__tests__/commands/version.test.ts
  packages/zenn-cli/src/server/__tests__/fixtures/images/test-1036bytes.jpg
  packages/zenn-cli/src/server/__tests__/fixtures/images/test.jpg
  packages/zenn-cli/src/server/__tests__/fixtures/markdown-body-only.md
  packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/server/commands/index.ts
  packages/zenn-cli/src/server/commands/init.ts
  packages/zenn-cli/src/server/commands/list-articles.ts
  packages/zenn-cli/src/server/commands/list-books.ts
  packages/zenn-cli/src/server/commands/new-article.ts
  packages/zenn-cli/src/server/commands/new-book.ts
  packages/zenn-cli/src/server/commands/preview.ts
  packages/zenn-cli/src/server/commands/version.ts
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: bugfix

#213 release: titleの最大文字数のバリデーションを修正/zenn-cliのテストを修正
  lerna.json
  packages/zenn-cli/articles/math.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/__tests__/lib/validator.test.ts
  packages/zenn-cli/src/client/lib/validator.ts
  packages/zenn-cli/src/server/__tests__/commands/help.test.ts
  packages/zenn-cli/src/server/__tests__/commands/index.test.ts
  packages/zenn-cli/src/server/__tests__/commands/init.test.ts
  packages/zenn-cli/src/server/__tests__/commands/new-article.test.ts
  packages/zenn-cli/src/server/__tests__/commands/new-book.test.ts
  packages/zenn-cli/src/server/__tests__/commands/preview.test.ts
  packages/zenn-cli/src/server/__tests__/commands/version.test.ts
  packages/zenn-cli/src/server/__tests__/fixtures/images/test-1036bytes.jpg
  packages/zenn-cli/src/server/__tests__/fixtures/images/test.jpg
  packages/zenn-cli/src/server/__tests__/fixtures/markdown-body-only.md
  packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/server/commands/index.ts
  packages/zenn-cli/src/server/commands/init.ts
  packages/zenn-cli/src/server/commands/list-articles.ts
  packages/zenn-cli/src/server/commands/list-books.ts
  packages/zenn-cli/src/server/commands/new-article.ts
  packages/zenn-cli/src/server/commands/new-book.ts
  packages/zenn-cli/src/server/commands/preview.ts
  packages/zenn-cli/src/server/commands/version.ts
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#214 mermaid.js のレンダリングを改善 / 縦幅の固定化を回避する
  .github/PULL_REQUEST_TEMPLATE.md
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-embed-elements/src/classes/mermaid.ts
Labels: fix
