Repository zenn-dev/zenn-editor, pull requests merged in 2021-11, with the labels that each got.

#220 本文のスタイルの微調整
  packages/zenn-content-css/src/_content.scss
  packages/zenn-content-css/src/_footnotes.scss
  packages/zenn-markdown-html/src/index.ts
Labels: enhancement

#221 Bump up mermaid.js from 8.12 to 8.13
  packages/zenn-cli/articles/mermaid.md
  packages/zenn-embed-elements/src/classes/mermaid.ts
Labels: fix

#222 release: 本文のスタイルの微調整 / mermaid.jsのバージョンアップ
  lerna.json
  packages/zenn-cli/articles/mermaid.md
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_content.scss
  packages/zenn-content-css/src/_footnotes.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-embed-elements/src/classes/mermaid.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/index.ts
Labels: release
