Repository zenn-dev/zenn-editor, pull requests merged in 2021-07, with the labels that each got.

#187 ZennCLIのプレビューでファイルの並び順をソートできるように
  packages/example/README.md
  packages/example/articles/.keep
  packages/example/articles/embed.md
  packages/example/articles/example.md
  packages/example/books/.keep
  packages/example/books/ef80dc98810c6a70ca1b/config.yaml
  packages/example/books/ef80dc98810c6a70ca1b/example1.md
  packages/example/books/ef80dc98810c6a70ca1b/example2.md
  packages/example/books/ef80dc98810c6a70ca1b/no-content.md
  packages/example/books/text-book-example/1.md
  packages/example/books/text-book-example/2.md
  packages/example/books/text-book-example/config.yml
  packages/example/package.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/Sidebar.tsx
  packages/zenn-cli/src/client/components/ValidationErrors.tsx
  packages/zenn-cli/src/client/components/books/show.tsx
  packages/zenn-cli/src/client/components/books/show/BookHeader.tsx
  packages/zenn-cli/src/client/components/chapters/show/ChapterHeader.tsx
  packages/zenn-cli/src/client/components/sidebar/Directory.tsx
  packages/zenn-cli/src/client/components/sidebar/ListItemInner.tsx
  packages/zenn-cli/src/client/components/sidebar/Settings.tsx
  packages/zenn-cli/src/client/public/icons/back.svg
  packages/zenn-cli/src/client/public/icons/error-exclamation.svg
  packages/zenn-cli/src/client/public/icons/open.svg
  packages/zenn-cli/src/client/public/icons/sidebar-fold.svg
  packages/zenn-cli/src/client/public/icons/sidebar-item-arrow.svg
  packages/zenn-cli/src/client/public/icons/sidebar-open.svg
  packages/zenn-cli/src/client/public/static-images/book-cover.png
  packages/zenn-cli/src/client/public/static-images/folder-close.svg
  packages/zenn-cli/src/client/public/static-images/folder-open.svg
  packages/zenn-cli/src/common/helper.ts
  packages/zenn-cli/src/common/types.ts
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-cli/src/server/lib/books.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-cli/src/server/preview/api/articles.ts
  packages/zenn-cli/src/server/preview/api/books.ts
  packages/zenn-content-css/src/_content.scss
  yarn.lock
Labels: feature

#188 release: Zenn CLIのソート機能
  lerna.json
  packages/example/README.md
  packages/example/articles/.keep
  packages/example/articles/embed.md
  packages/example/articles/example.md
  packages/example/books/.keep
  packages/example/books/ef80dc98810c6a70ca1b/config.yaml
  packages/example/books/ef80dc98810c6a70ca1b/example1.md
  packages/example/books/ef80dc98810c6a70ca1b/example2.md
  packages/example/books/ef80dc98810c6a70ca1b/no-content.md
  packages/example/books/text-book-example/1.md
  packages/example/books/text-book-example/2.md
  packages/example/books/text-book-example/config.yml
  packages/example/package.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/Sidebar.tsx
  packages/zenn-cli/src/client/components/ValidationErrors.tsx
  packages/zenn-cli/src/client/components/books/show.tsx
  packages/zenn-cli/src/client/components/books/show/BookHeader.tsx
  packages/zenn-cli/src/client/components/chapters/show/ChapterHeader.tsx
  packages/zenn-cli/src/client/components/sidebar/Directory.tsx
  packages/zenn-cli/src/client/components/sidebar/ListItemInner.tsx
  packages/zenn-cli/src/client/components/sidebar/Settings.tsx
  packages/zenn-cli/src/client/public/icons/back.svg
  packages/zenn-cli/src/client/public/icons/error-exclamation.svg
  packages/zenn-cli/src/client/public/icons/open.svg
  packages/zenn-cli/src/client/public/icons/sidebar-fold.svg
  packages/zenn-cli/src/client/public/icons/sidebar-item-arrow.svg
  packages/zenn-cli/src/client/public/icons/sidebar-open.svg
  packages/zenn-cli/src/client/public/static-images/book-cover.png
  packages/zenn-cli/src/client/public/static-images/folder-close.svg
  packages/zenn-cli/src/client/public/static-images/folder-open.svg
  packages/zenn-cli/src/common/helper.ts
  packages/zenn-cli/src/common/types.ts
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-cli/src/server/lib/books.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-cli/src/server/preview/api/articles.ts
  packages/zenn-cli/src/server/preview/api/books.ts
  packages/zenn-cli/src/server/preview/app.ts
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_content.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#189 スタイルの改善
  packages/zenn-content-css/src/_content.scss
Labels: enhancement

#190 prismjsを^1.24.1にアップデート
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: enhancement

#191 release: スタイルの調整とprismjsのアップデート
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_content.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#192 viteでのみ参照するdependenciesをdevDependenciesに変更
  packages/zenn-cli/package.json
Labels: chore

#194 zenn previewでローカルに配置した画像のプレビューとバリデーションに対応
  packages/zenn-cli/.gitignore
  packages/zenn-cli/articles/example-images.md
  packages/zenn-cli/books/chapter-by-filename/4.exmple-images.md
  packages/zenn-cli/images/example-images/zenn-editor.png
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/Sidebar.tsx
  packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/server/__tests__/preview/app.test.ts
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-cli/src/server/lib/books.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-cli/src/server/preview/app.ts
  packages/zenn-cli/vite.config.ts
  yarn.lock
Labels: feature

#195 ドキュメントに画像の管理についての説明を追加
  packages/zenn-cli/src/client/components/Routes.tsx
  packages/zenn-cli/src/client/components/Sidebar.tsx
  packages/zenn-cli/src/client/components/guide/index.tsx
  packages/zenn-cli/src/client/components/home/index.tsx
  packages/zenn-cli/src/server/preview/api/cli-guide.ts
  packages/zenn-cli/src/server/preview/app.ts
Labels: chore

#196 release: 画像のプレビューに対応
  CONTRIBUTING.md
  lerna.json
  packages/zenn-cli/.gitignore
  packages/zenn-cli/articles/example-images.md
  packages/zenn-cli/books/chapter-by-filename/4.exmple-images.md
  packages/zenn-cli/images/example-images/zenn-editor.png
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/Routes.tsx
  packages/zenn-cli/src/client/components/Sidebar.tsx
  packages/zenn-cli/src/client/components/guide/index.tsx
  packages/zenn-cli/src/client/components/home/index.tsx
  packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/server/__tests__/preview/app.test.ts
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-cli/src/server/lib/books.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-cli/src/server/preview/api/cli-guide.ts
  packages/zenn-cli/src/server/preview/app.ts
  packages/zenn-cli/src/server/zenn.ts
  packages/zenn-cli/vite.config.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#197 `getWorkingPath()`で連続した`.`に対して常にエラーを発生させるように
  packages/zenn-cli/src/server/lib/helper.ts
Labels: fix

#198 release: force getWorkingPath not to include any consecutive dots
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
Labels: release

#199 Linterの修正
  .eslintrc.js
  packages/zenn-cli/README.md
  packages/zenn-cli/articles/README.md
  packages/zenn-cli/articles/empty.md
  packages/zenn-cli/articles/example-full.md
  packages/zenn-cli/articles/example-tweets.md
  packages/zenn-cli/articles/example.md
  packages/zenn-cli/articles/link-card.md
  packages/zenn-cli/articles/math.md
  packages/zenn-cli/articles/no-frontmatters.md
  packages/zenn-cli/articles/xss.md
  packages/zenn-cli/books/README.md
  packages/zenn-cli/books/chapter-by-config/about.md
  packages/zenn-cli/books/chapter-by-filename/1.about.md
  packages/zenn-cli/books/chapter-by-filename/2.hello-world.md
  packages/zenn-cli/books/chapter-by-filename/3.c++.md
  packages/zenn-cli/books/chapter-by-filename/3.cpp.md
  packages/zenn-cli/books/chapter-by-filename/999.conclusion.md
  packages/zenn-cli/books/chapter-by-filename/conclusion.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/__tests__/fixtures/articles/my-first-post.md
  packages/zenn-cli/src/server/__tests__/fixtures/articles/my-second-post.md
  packages/zenn-cli/src/server/__tests__/fixtures/books/my-first-book/example1.md
  packages/zenn-cli/src/server/__tests__/fixtures/books/my-first-book/example2.md
  packages/zenn-cli/src/server/__tests__/fixtures/books/my-first-book/example3.md
  packages/zenn-cli/src/server/__tests__/fixtures/books/my-second-book/1.hi.md
  packages/zenn-cli/src/server/__tests__/fixtures/books/my-second-book/2.hey.md
  packages/zenn-cli/src/server/__tests__/fixtures/books/my-second-book/invalid-slug.md
  packages/zenn-cli/src/server/__tests__/fixtures/markdown-body-only.md
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-embed-elements/.eslintrc.yml
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/.eslintrc.yml
  packages/zenn-markdown-html/package.json
Labels: chore

#200 eslintの警告を解消
  .github/workflows/lint.yml
  package.json
  packages/zenn-cli/.eslintrc.yml
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/Routes.tsx
  packages/zenn-embed-elements/.eslintrc.yml
  packages/zenn-embed-elements/package.json
  packages/zenn-embed-elements/src/classes/mermaid.ts
  packages/zenn-markdown-html/.eslintrc.yml
  packages/zenn-markdown-html/__tests__/br.test.ts
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/md-br.ts
  packages/zenn-markdown-html/src/utils/md-container.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  packages/zenn-markdown-html/src/utils/md-katex.ts
Labels: chore
