Repository zenn-dev/zenn-editor, pull requests merged in 2021-08, with the labels that each got.

#201 画像ファイルの存在確認とファイルサイズの検証を追加
  packages/zenn-cli/articles/example-images.md
  packages/zenn-cli/src/client/__tests__/lib/validator.test.ts
  packages/zenn-cli/src/client/lib/validator.ts
  packages/zenn-cli/src/server/lib/helper.ts
Labels: fix

#202 bump markdown-it-anchor
  packages/zenn-markdown-html/__tests__/basic.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/@types/markdown-it-anchor.d.ts
  packages/zenn-markdown-html/src/index.ts
  yarn.lock
Labels: chore

#209 KaTeXのインライン記法であっても長さに応じて横スクロールするように
  packages/zenn-cli/articles/math.md
  packages/zenn-content-css/src/_embed.scss
Labels: bugfix
