Repository zenn-dev/zenn-editor, pull requests merged in 2022-03, with the labels that each got.

#268 メッセージ記法のアイコンを上下中央から上揃えへと変更
  packages/zenn-content-css/src/_message.scss
Labels: enhancement

#269 埋め込み要素を表示するコンポーネントのpostMessage処理を修正
  packages/zenn-cli/articles/zenn-embed-examples.md
  packages/zenn-cli/src/client/components/App.tsx
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-embed-components/src/components/SendWindowSize/index.tsx
  packages/zenn-embed-components/src/embed/gist/EmbedGist.tsx
  packages/zenn-embed-components/src/embed/gist/gist.stories.tsx
  packages/zenn-embed-components/src/embed/gist/index.tsx
  packages/zenn-embed-components/src/embed/gist/types.ts
  packages/zenn-embed-components/src/embed/github/EmbedGithub.tsx
  packages/zenn-embed-components/src/embed/github/github.stories.tsx
  packages/zenn-embed-components/src/embed/github/utils.ts
  packages/zenn-embed-components/src/embed/link-card/EmbedBaseLinkCard.tsx
  packages/zenn-embed-components/src/embed/link-card/EmbedGithubLinkCard.tsx
  packages/zenn-embed-components/src/embed/link-card/EmbedLinkCard.tsx
  packages/zenn-embed-components/src/embed/link-card/index.tsx
  packages/zenn-embed-components/src/embed/link-card/link-card.stories.tsx
  packages/zenn-embed-components/src/embed/link-card/types.ts
  packages/zenn-embed-components/src/embed/mermaid/EmbedMermaid.tsx
  packages/zenn-embed-components/src/embed/mermaid/EmbedMermaidError.tsx
  packages/zenn-embed-components/src/embed/mermaid/EmbedMermaidLoading.tsx
  packages/zenn-embed-components/src/embed/mermaid/mermaid.stories.tsx
  packages/zenn-embed-components/src/embed/mermaid/types.ts
  packages/zenn-embed-components/src/embed/mermaid/utils.ts
  packages/zenn-embed-components/src/embed/tweet/EmbedTweet.tsx
  packages/zenn-embed-components/src/embed/tweet/tweet.stories.tsx
  packages/zenn-embed-components/src/embed/types.ts
  packages/zenn-embed-components/src/events/resize.ts
  packages/zenn-embed-components/src/index.ts
  packages/zenn-markdown-html/src/utils/helper.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  packages/zenn-markdown-html/src/utils/md-linkify-to-card.ts
  packages/zenn-markdown-html/src/utils/md-renderer-fence.ts
Labels: bugfix, feature

#274 #273 `:::message` 記法のセマンティクス拡充
  packages/zenn-content-css/src/_message.scss
  packages/zenn-content-css/test.html
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/src/utils/md-container.ts
Labels: enhancement

#275 :::message をflexを使う形に修正
  packages/zenn-content-css/src/_message.scss
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/src/utils/md-container.ts
Labels: enhancement

#277 タスクリストでチェックの下にドットが見えてしまう問題の修正
  packages/zenn-content-css/src/_content.scss
Labels: bugfix

#276 v0.1.108
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_content.scss
  packages/zenn-content-css/src/_message.scss
  packages/zenn-content-css/test.html
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/md-container.ts
  yarn.lock
Labels: release

#279 fix: message内のコードブロックがはみ出してしまうバグを修正
  packages/zenn-content-css/src/_message.scss
Labels: bugfix

#280 feat: 印刷時にdetailsを開くようにした
  packages/zenn-cli/src/client/components/BodyContent.tsx
  packages/zenn-cli/src/client/components/PrintDetailsOpener.tsx
Labels: feature
