Repository zenn-dev/zenn-editor, pull requests merged in 2022-02, with the labels that each got.

#253 feat: emotionを使えるように環境構築した
  packages/zenn-embed-components/.storybook/main.js
  packages/zenn-embed-components/package.json
  packages/zenn-embed-components/tsconfig.json
  yarn.lock
Labels: feature

#256 feat: 埋め込み用のLinkCardコンポーネントの追加
  packages/zenn-embed-components/src/components/Icons/GithubCodeIcon.tsx
  packages/zenn-embed-components/src/components/Icons/GithubForkIcon.tsx
  packages/zenn-embed-components/src/components/Icons/GithubIcon.tsx
  packages/zenn-embed-components/src/components/Icons/GithubStarIcon.tsx
  packages/zenn-embed-components/src/components/link-card/EmbedBaseLinkCard.tsx
  packages/zenn-embed-components/src/components/link-card/EmbedGithubLinkCard.tsx
  packages/zenn-embed-components/src/components/link-card/EmbedLinkCardPlaceholder.tsx
  packages/zenn-embed-components/src/components/link-card/index.tsx
  packages/zenn-embed-components/src/components/link-card/link-card.stories.tsx
  packages/zenn-embed-components/src/components/link-card/types.ts
Labels: feature

#257 refactor: 埋め込み用のGithubコンポーネントをリファクタリングした
  packages/zenn-embed-components/src/components/github/EmbedGitHubError.tsx
  packages/zenn-embed-components/src/components/github/EmbedGithubHeader.tsx
  packages/zenn-embed-components/src/components/github/EmbedGithubLoading.tsx
  packages/zenn-embed-components/src/components/github/GithubIcon.tsx
  packages/zenn-embed-components/src/components/github/github-css.ts
  packages/zenn-embed-components/src/components/github/github-header.tsx
  packages/zenn-embed-components/src/components/github/github-loading.tsx
  packages/zenn-embed-components/src/components/github/index.tsx
  packages/zenn-embed-components/src/components/github/styles.ts
Labels: fix, feature

#258 fix: `zenn-embed-components` のビルド設定を修正
  packages/zenn-embed-components/package.json
  packages/zenn-embed-components/tsconfig.build.json
  packages/zenn-embed-components/tsconfig.json
Labels: enhancement, feature

#254 fix: twitterのURLに'&'が含まれていると正規表現にマッチしないバグを修正
  packages/zenn-cli/articles/example-tweets.md
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: bugfix

#259 markdown内のリンクを別タブで開くように
  packages/zenn-cli/package.json
  packages/zenn-markdown-html/__tests__/basic.test.ts
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/dollar.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/src/index.ts
  yarn.lock
Labels: enhancement

#261 feat: Twitterカードの埋め込みコンポーネントを実装した
  packages/zenn-embed-components/.storybook/preview-head.html
  packages/zenn-embed-components/src/components/Icons/GithubStarIcon.tsx
  packages/zenn-embed-components/src/components/tweet/index.tsx
  packages/zenn-embed-components/src/components/tweet/tweet.stories.tsx
Labels: feature

#263 feat: Gistの埋め込みコンポーネントを実装した
  packages/zenn-embed-components/package.json
  packages/zenn-embed-components/src/components/gist/EmbedGistError.tsx
  packages/zenn-embed-components/src/components/gist/EmbedGistLoading.tsx
  packages/zenn-embed-components/src/components/gist/gist.stories.tsx
  packages/zenn-embed-components/src/components/gist/index.tsx
Labels: feature

#262 ツイート埋め込みの正規表現を調整
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: enhancement

#260 release: ツイート埋め込みの正規表現の調整 / リンクのtarget属性を調整
  lerna.json
  packages/zenn-cli/articles/example-tweets.md
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/basic.test.ts
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/dollar.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/index.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
  yarn.lock
Labels: release

#265 prism.jsのアップデート
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: dependencies, fix
