Repository zenn-dev/zenn-editor, pull requests merged in 2022-04, with the labels that each got.

#271 feat: WebComponentsをなるべく廃止し、iframeを用いて埋め込み要素を表示するようにした
  packages/zenn-cli/articles/zenn-embed-examples.md
  packages/zenn-cli/src/client/components/App.tsx
  packages/zenn-cli/src/client/hooks/useListenEmbeddedMessage.ts
  packages/zenn-cli/src/server/commands/init.ts
  packages/zenn-cli/src/server/commands/list-articles.ts
  packages/zenn-cli/src/server/commands/list-books.ts
  packages/zenn-cli/src/server/commands/new-article.ts
  packages/zenn-cli/src/server/commands/new-book.ts
  packages/zenn-cli/src/server/lib/books.ts
  packages/zenn-cli/tsconfig.json
  packages/zenn-cli/vite.config.ts
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-embed-elements/src/classes/gist.ts
  packages/zenn-embed-elements/src/classes/mermaid.ts
  packages/zenn-embed-elements/src/classes/tweet.ts
  packages/zenn-embed-elements/src/index.ts
  packages/zenn-embed-elements/src/init-twitter-script-inner.ts
  packages/zenn-embed-elements/src/utils/jsonp.ts
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/__tests__/mermaid.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/helper.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  packages/zenn-markdown-html/src/utils/md-linkify-to-card.ts
  packages/zenn-markdown-html/src/utils/md-renderer-fence.ts
  packages/zenn-markdown-html/tsconfig.build.json
  packages/zenn-markdown-html/tsconfig.json
  yarn.lock
Labels: enhancement, feature

#283 fix: link-cardの場合はiframeの高さを固定にするように修正
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/mermaid.test.ts
  packages/zenn-markdown-html/src/utils/helper.ts
Labels: bugfix

#285 zenn-embeddedに関する微調整
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-markdown-html/src/utils/helper.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  yarn.lock
Labels: enhancement

#286 fix: リポジトリ名にドットが入っているリンクがGithubの埋め込みとして表示されないバグを修正
  packages/zenn-markdown-html/__tests__/matchers/isGithubUrl.test.ts
  packages/zenn-markdown-html/src/utils/helper.ts
Labels: bugfix

#287 release v0.1.109
  lerna.json
  packages/zenn-cli/articles/zenn-embed-examples.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/App.tsx
  packages/zenn-cli/src/client/components/BodyContent.tsx
  packages/zenn-cli/src/client/components/PrintDetailsOpener.tsx
  packages/zenn-cli/src/client/hooks/useListenEmbeddedMessage.ts
  packages/zenn-cli/src/server/commands/init.ts
  packages/zenn-cli/src/server/commands/list-articles.ts
  packages/zenn-cli/src/server/commands/list-books.ts
  packages/zenn-cli/src/server/commands/new-article.ts
  packages/zenn-cli/src/server/commands/new-book.ts
  packages/zenn-cli/src/server/lib/books.ts
  packages/zenn-cli/tsconfig.json
  packages/zenn-cli/vite.config.ts
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-content-css/src/_message.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-embed-elements/src/classes/gist.ts
  packages/zenn-embed-elements/src/classes/mermaid.ts
  packages/zenn-embed-elements/src/classes/tweet.ts
  packages/zenn-embed-elements/src/index.ts
  packages/zenn-embed-elements/src/init-twitter-script-inner.ts
  packages/zenn-embed-elements/src/utils/jsonp.ts
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isGithubUrl.test.ts
  packages/zenn-markdown-html/__tests__/mermaid.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/helper.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  packages/zenn-markdown-html/src/utils/md-linkify-to-card.ts
  packages/zenn-markdown-html/src/utils/md-renderer-fence.ts
  packages/zenn-markdown-html/tsconfig.build.json
  packages/zenn-markdown-html/tsconfig.json
  yarn.lock
Labels: release

#288 未使用のcssを削除
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-content-css/src/_footnotes.scss
Labels: chore
