Repository zenn-dev/zenn-editor, pull requests merged in 2022-06, with the labels that each got.

#294 articleのpreviewにてpublished_atをサポート
  packages/zenn-cli/articles/code-fence.md
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/articles/math.md
  packages/zenn-cli/articles/mermaid.md
  packages/zenn-cli/articles/xss.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/ValidationErrors.tsx
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/lib/validator.ts
  packages/zenn-cli/src/common/types.ts
  packages/zenn-cli/src/server/__tests__/fixtures/markdown-body-only.md
  packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/server/lib/articles.ts
  yarn.lock
Labels: enhancement

#298 published_atをcamelCaseに修正
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/lib/validator.ts
Labels: fix

#299 publishedAtをsnake_caseに修正
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/lib/validator.ts
  packages/zenn-cli/src/common/types.ts
Labels: fix

#300 release v0.1.111
  lerna.json
  packages/zenn-cli/articles/code-fence.md
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/articles/math.md
  packages/zenn-cli/articles/mermaid.md
  packages/zenn-cli/articles/xss.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/ValidationErrors.tsx
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/lib/validator.ts
  packages/zenn-cli/src/common/types.ts
  packages/zenn-cli/src/server/__tests__/fixtures/markdown-body-only.md
  packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/helper.ts
  yarn.lock
Labels: release

#301 feat: `zenn-cli` から dependencies を無くすように webpack でバンドルするように修正
  packages/zenn-cli/README.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/__tests__/preview/app.test.ts
  packages/zenn-cli/src/server/api/articles.ts
  packages/zenn-cli/src/server/api/books.ts
  packages/zenn-cli/src/server/api/cli-guide.ts
  packages/zenn-cli/src/server/api/cli-version.ts
  packages/zenn-cli/src/server/api/local-info.ts
  packages/zenn-cli/src/server/app.ts
  packages/zenn-cli/src/server/commands/preview.ts
  packages/zenn-cli/webpack.server.js
  packages/zenn-markdown-html/.babelrc.json
  packages/zenn-markdown-html/README.md
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/jest.config.js
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/prism-plugins/prism-diff-highlight.ts
  packages/zenn-markdown-html/src/utils/highlight.ts
  packages/zenn-markdown-html/tsconfig.build.json
  yarn.lock
Labels: feature

#302 release v0.1.112
  lerna.json
  packages/zenn-cli/README.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/__tests__/preview/app.test.ts
  packages/zenn-cli/src/server/api/articles.ts
  packages/zenn-cli/src/server/api/books.ts
  packages/zenn-cli/src/server/api/cli-guide.ts
  packages/zenn-cli/src/server/api/cli-version.ts
  packages/zenn-cli/src/server/api/local-info.ts
  packages/zenn-cli/src/server/app.ts
  packages/zenn-cli/src/server/commands/preview.ts
  packages/zenn-cli/webpack.server.js
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/.babelrc.json
  packages/zenn-markdown-html/README.md
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/jest.config.js
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/prism-plugins/prism-diff-highlight.ts
  packages/zenn-markdown-html/src/utils/highlight.ts
  packages/zenn-markdown-html/tsconfig.build.json
  yarn.lock
Labels: release

#303 feat: zenn-cli の更新が必要な時は cli 上にも表示するように修正
  packages/zenn-cli/jest.config.server.js
  packages/zenn-cli/nodemon.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/__tests__/commands/index.test.ts
  packages/zenn-cli/src/server/__tests__/lib/notify-update.test.ts
  packages/zenn-cli/src/server/commands/index.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-cli/src/server/lib/notify-update.ts
  packages/zenn-cli/src/server/zenn.ts
  yarn.lock
Labels: feature

#304 feat: zenn-cliのビルドファイルにpackage.jsonを含めないように修正
  packages/zenn-cli/webpack.server.js
Labels: bugfix

#306 release v0.1.113
  lerna.json
  packages/zenn-cli/jest.config.server.js
  packages/zenn-cli/nodemon.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/App.tsx
  packages/zenn-cli/src/client/hooks/useListenEmbeddedMessage.ts
  packages/zenn-cli/src/client/index.html
  packages/zenn-cli/src/server/__tests__/commands/index.test.ts
  packages/zenn-cli/src/server/__tests__/lib/notify-update.test.ts
  packages/zenn-cli/src/server/commands/index.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-cli/src/server/lib/notify-update.ts
  packages/zenn-cli/src/server/zenn.ts
  packages/zenn-cli/webpack.server.js
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#307 front matter で publication_name を受け付けるように修正
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/src/client/__tests__/lib/validator.test.ts
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/index.html
  packages/zenn-cli/src/client/lib/validator.ts
  packages/zenn-cli/src/common/types.ts
Labels: feature

#309 zenn-cliが実行時エラーになるバグを修正
  packages/zenn-cli/package.json
  packages/zenn-cli/webpack.server.js
Labels: bugfix

#311 dep: got のバージョンをあげた
  yarn.lock
Labels: dependencies, chore

#310 release v0.1.114
  lerna.json
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/__tests__/lib/validator.test.ts
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/index.html
  packages/zenn-cli/src/client/lib/validator.ts
  packages/zenn-cli/src/common/types.ts
  packages/zenn-cli/webpack.server.js
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#312 chore: Fixed command argument character length.
  packages/zenn-cli/README.md
Labels: fix
