Repository zenn-dev/zenn-editor, pull requests merged in 2022-09, with the labels that each got.

#348 material-icons のために導入していた material-ui を廃止し、かわりに react-icons/md を導入した
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/Sidebar.tsx
  packages/zenn-cli/src/client/components/ValidationErrors.tsx
  packages/zenn-cli/src/client/components/books/show.tsx
  packages/zenn-cli/src/client/components/chapters/show/ChapterHeader.tsx
  packages/zenn-cli/src/client/components/sidebar/Directory.tsx
  packages/zenn-cli/src/client/components/sidebar/ListItemInner.tsx
  packages/zenn-cli/src/client/components/sidebar/Settings.tsx
  packages/zenn-cli/src/client/lib/validator.ts
  yarn.lock
Labels: fix, feature

#350 fix: タスクリストのサブリストのリストマーカーを表示するように修正
  packages/zenn-content-css/src/_content.scss
Labels: fix

#349 markdownToSimpleHtmlを追加
  packages/zenn-markdown-html/README.md
  packages/zenn-markdown-html/__tests__/markdown-simple-html.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/index.ts
  packages/zenn-markdown-html/src/markdown-to-simple-html.ts
  packages/zenn-markdown-html/src/utils/md-link-attributes.ts
  yarn.lock
Labels: feature

#355 figma と blueprintue の埋め込みを追加した
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: feature

#354 feat: details内でもLinkifyの埋め込みをできるようにした
  packages/zenn-cli/articles/link-card.md
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/src/utils/md-linkify-to-card.ts
Labels: feature

#356 release: v0.1.122
  lerna.json
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-cli/articles/link-card.md
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/README.md
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/__tests__/markdown-simple-html.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/index.ts
  packages/zenn-markdown-html/src/markdown-to-simple-html.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  packages/zenn-markdown-html/src/utils/md-link-attributes.ts
  packages/zenn-markdown-html/src/utils/md-linkify-to-card.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
  yarn.lock
Labels: release

#357 fix: figmaとblueprintue の埋め込み枠を16:9にした
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
Labels: fix

#358 release 0.1.123
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
Labels: release

#359 fix: ensure embed safety
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
Labels: bugfix

#361 FigmaとblueprintUEの埋め込み要素の正規表現を修正
  packages/zenn-markdown-html/__tests__/matchers/isBlueprintUEUrl.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isFigmaUrl.test.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: bugfix

#360 release v0.1.124
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/matchers/isBlueprintUEUrl.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isFigmaUrl.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: release

#362 fix: テストエラーを修正
  packages/zenn-markdown-html/__tests__/matchers/isBlueprintUEUrl.test.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: bugfix

#363 release v0.1.125
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/matchers/isBlueprintUEUrl.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: release

#366 fix: URLに`_`が含まれているとblueprintが埋め込めないバグを修正
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: bugfix

#367 feat: Pull Requeset 作成時に注意事項をコメントする GitHub Actions を追加した
  .github/workflows/policy-comment.yml
  docs/pull_request_policy.md
Labels: feature

#371 feat: LinkCard以外の埋め込みURL文字数制限をかけるように修正
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isGithubUrl.test.ts
  packages/zenn-markdown-html/src/utils/embed-helper.ts
  packages/zenn-markdown-html/src/utils/helper.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  packages/zenn-markdown-html/src/utils/md-linkify-to-card.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: feature

#373 new:article に --publication-name オプションを追加
  packages/zenn-cli/src/server/__tests__/commands/new-article.test.ts
  packages/zenn-cli/src/server/commands/new-article.ts
  packages/zenn-cli/src/server/lib/messages.ts
Labels: feature

#374 fix: githubの埋め込みURLには制限をかけないように修正
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/src/utils/embed-helper.ts
  packages/zenn-markdown-html/src/utils/helper.ts
  packages/zenn-markdown-html/src/utils/md-renderer-fence.ts
Labels: fix

#369 release v0.1.126
  .github/workflows/policy-comment.yml
  docs/pull_request_policy.md
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/__tests__/commands/new-article.test.ts
  packages/zenn-cli/src/server/commands/new-article.ts
  packages/zenn-cli/src/server/lib/messages.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isGithubUrl.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/embed-helper.ts
  packages/zenn-markdown-html/src/utils/helper.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  packages/zenn-markdown-html/src/utils/md-linkify-to-card.ts
  packages/zenn-markdown-html/src/utils/md-renderer-fence.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: release

#375 fix: 埋め込み要素のタイプ判定をより安全な形へ修正
  packages/zenn-markdown-html/src/utils/embed-helper.ts
Labels: fix

#376 release v0.1.127
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/embed-helper.ts
Labels: release

#370 許可リストによるサニタイズ
  lerna.json
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/src/client/components/TemporarySanitizeMessageBar.tsx
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/components/chapters/show/ChapterHeader.tsx
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-content-css/test.html
  packages/zenn-markdown-html/README.md
  packages/zenn-markdown-html/__tests__/basic.test.ts
  packages/zenn-markdown-html/__tests__/br.test.ts
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/dollar.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/__tests__/markdown-simple-html.test.ts
  packages/zenn-markdown-html/__tests__/mermaid.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/index.ts
  packages/zenn-markdown-html/src/markdown-to-simple-html.ts
  packages/zenn-markdown-html/src/sanitizer.ts
  packages/zenn-markdown-html/src/utils/embed-helper.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  yarn.lock
Labels: feature

#377 release v0.1.127
  lerna.json
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/TemporarySanitizeMessageBar.tsx
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/components/chapters/show/ChapterHeader.tsx
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-content-css/test.html
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/README.md
  packages/zenn-markdown-html/__tests__/basic.test.ts
  packages/zenn-markdown-html/__tests__/br.test.ts
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/dollar.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/__tests__/markdown-simple-html.test.ts
  packages/zenn-markdown-html/__tests__/mermaid.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/index.ts
  packages/zenn-markdown-html/src/markdown-to-simple-html.ts
  packages/zenn-markdown-html/src/sanitizer.ts
  packages/zenn-markdown-html/src/utils/embed-helper.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  yarn.lock
Labels: release
