Repository zenn-dev/zenn-editor, pull requests merged in 2022-01, with the labels that each got.

#231 `color`をv1.4.0に固定
  packages/zenn-cli/package.json
  yarn.lock
Labels: bugfix

#232 release: colorsのバージョンを固定
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#233 Chrome 97から`<details>`内でKatexやmermaidがレンダリングされない問題の解消
  packages/zenn-cli/articles/math.md
  packages/zenn-cli/articles/mermaid.md
  packages/zenn-embed-elements/src/classes/katex.ts
  packages/zenn-embed-elements/src/classes/mermaid.ts
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: bugfix

#234 release: Chromeにおいてdetailsタグ内でkatexやmermaid記法が表示されない問題の修正
  lerna.json
  packages/zenn-cli/articles/math.md
  packages/zenn-cli/articles/mermaid.md
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-embed-elements/src/classes/katex.ts
  packages/zenn-embed-elements/src/classes/mermaid.ts
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#237 markdown-itをv12にアップデート
  packages/zenn-cli/articles/code-fence.md
  packages/zenn-content-css/src/_content.scss
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: enhancement, dependencies

#235 fix: mermaid.jsがsafariのdetails内でレンダリングされない問題
  packages/zenn-embed-elements/src/classes/mermaid.ts
Labels: bugfix

#239 release: mermaid.js の遅延読み込み対応、markdown-it のバージョンアップ
  lerna.json
  packages/zenn-cli/articles/code-fence.md
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_content.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-embed-elements/src/classes/mermaid.ts
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#238 KaTeXの正規表現修正
  packages/zenn-cli/articles/math.md
  packages/zenn-markdown-html/__tests__/dollar.test.ts
  packages/zenn-markdown-html/src/utils/md-katex.ts
Labels: bugfix

#243 release: 数式検出の正規表現を修正、bump nanoid
  lerna.json
  packages/zenn-cli/articles/math.md
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/dollar.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/md-katex.ts
  yarn.lock
Labels: release

#246 release: bump node-fetch, trim-offnewlines
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: dependencies, fix

#241 feat: @swc/jestを使ってテストを高速化
  packages/zenn-cli/jest.config.client.js
  packages/zenn-cli/jest.config.server.js
  packages/zenn-cli/package.json
  packages/zenn-markdown-html/jest.config.js
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: enhancement

#247 feat: `preview` コマンドに `host` オプションを追加
  packages/zenn-cli/src/server/__tests__/commands/preview.test.ts
  packages/zenn-cli/src/server/commands/preview.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-cli/src/server/lib/messages.ts
  packages/zenn-cli/src/server/lib/server.ts
  packages/zenn-cli/tsconfig.json
Labels: feature

#248 fix: tsx の差分フォーマットで余分な一行が表示されてしまうバグを修正
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/prism-plugins/prism-diff-highlight.ts
  packages/zenn-markdown-html/src/utils/highlight.ts
  yarn.lock
Labels: bugfix

#249 chore: bump node-fetch
  packages/zenn-cli/package.json
  yarn.lock
Labels: chore

#250 release: `host` option / enhance diff highlight
  lerna.json
  packages/zenn-cli/jest.config.client.js
  packages/zenn-cli/jest.config.server.js
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/__tests__/commands/preview.test.ts
  packages/zenn-cli/src/server/commands/preview.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-cli/src/server/lib/messages.ts
  packages/zenn-cli/src/server/lib/server.ts
  packages/zenn-cli/tsconfig.json
  packages/zenn-markdown-html/jest.config.js
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/prism-plugins/prism-diff-highlight.ts
  packages/zenn-markdown-html/src/utils/highlight.ts
  yarn.lock
Labels: release
