Repository zenn-dev/zenn-editor, pull requests merged in 2022-12, with the labels that each got.

#395 変換したHTMLに含まれるsvgタグを安全なタグに変更
  packages/zenn-content-css/src/_message.scss
  packages/zenn-content-css/test.html
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/src/utils/md-container.ts
Labels: fix

#397 release v0.1.133
  README.md
  lerna.json
  packages/zenn-cli/README.md
  packages/zenn-cli/package.json
  packages/zenn-content-css/README.md
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_message.scss
  packages/zenn-content-css/test.html
  packages/zenn-embed-elements/README.md
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/README.md
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/md-container.ts
  packages/zenn-validator/README.md
  packages/zenn-validator/package.json
  yarn.lock
Labels: release

#399 サニタイズリストからsvgを削除
  packages/zenn-content-css/src/_message.scss
  packages/zenn-markdown-html/src/sanitizer.ts
Labels: fix

#398 サニタイズにともなう後方互換のためのCSSを削除した
  packages/zenn-content-css/src/_embed.scss
Labels: chore

#401 release v0.1.134
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-cli/vite.config.ts
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-content-css/src/_message.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/sanitizer.ts
  packages/zenn-validator/package.json
  packages/zenn-validator/tsconfig.json
Labels: release

#405 Move contents type definition
  packages/zenn-cli/src/client/components/Sidebar.tsx
  packages/zenn-cli/src/client/components/articles/show.tsx
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/components/books/show.tsx
  packages/zenn-cli/src/client/components/books/show/BookChapterList.tsx
  packages/zenn-cli/src/client/components/books/show/BookHeader.tsx
  packages/zenn-cli/src/client/components/chapters/show.tsx
  packages/zenn-cli/src/client/components/chapters/show/ChapterHeader.tsx
  packages/zenn-cli/src/common/types.ts
  packages/zenn-cli/src/server/commands/list-articles.ts
  packages/zenn-cli/src/server/commands/list-books.ts
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-cli/src/server/lib/books.ts
  packages/zenn-validator/src/index.ts
  packages/zenn-validator/src/types.ts
Labels: feature
