Repository zenn-dev/zenn-editor, pull requests merged in 2022-10, with the labels that each got.

#380 fix: safari で `published_at` 指定時にエラーが発生してしまうバグを修正
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/lib/validator.ts
Labels: bugfix

#383 figma のフレームを埋め込めるように正規表現を修正した
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-cli/articles/zenn-embed-examples.md
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: bugfix

#381 release v0.1.129
  lerna.json
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-cli/articles/zenn-embed-examples.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/lib/validator.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: release

#378 埋め込みコンテンツに関するドキュメントを最新の内容に修正
  CONTRIBUTING.md
  README.md
  packages/zenn-embed-elements/README.md
Labels: chore

#379 :::message記法内でdetails/summaryやlink-cardが使われたときに見た目がやや崩れる問題を解消
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-content-css/src/_content.scss
  packages/zenn-content-css/src/_message.scss
Labels: fix

#384 release v0.1.130
  CONTRIBUTING.md
  README.md
  lerna.json
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_content.scss
  packages/zenn-content-css/src/_message.scss
  packages/zenn-embed-elements/README.md
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
Labels: release

#385 imagesディレクトリからwebp画像を読み込めるように
  packages/zenn-cli/articles/example-images.md
  packages/zenn-cli/books/chapter-by-filename/cover.png
  packages/zenn-cli/books/empty-book/cover.jpeg
  packages/zenn-cli/books/empty-book/cover.webp
  packages/zenn-cli/images/example-images/zenn-editor.webp
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/api/books.ts
  packages/zenn-cli/src/server/lib/books.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-content-css/src/_content.scss
  yarn.lock
Labels: feature

#386 release v0.1.131
  lerna.json
  packages/zenn-cli/articles/example-images.md
  packages/zenn-cli/books/chapter-by-filename/cover.png
  packages/zenn-cli/books/empty-book/cover.jpeg
  packages/zenn-cli/books/empty-book/cover.webp
  packages/zenn-cli/images/example-images/zenn-editor.webp
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/api/books.ts
  packages/zenn-cli/src/server/lib/books.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_content.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#382 バリデーション処理を別パッケージとして切り出すように修正
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/ValidationErrors.tsx
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/components/books/show/BookHeader.tsx
  packages/zenn-cli/src/client/components/chapters/show/ChapterHeader.tsx
  packages/zenn-validator/.eslintrc.yml
  packages/zenn-validator/.gitignore
  packages/zenn-validator/README.md
  packages/zenn-validator/__tests__/validator.test.ts
  packages/zenn-validator/jest.config.js
  packages/zenn-validator/package.json
  packages/zenn-validator/src/index.ts
  packages/zenn-validator/src/types.ts
  packages/zenn-validator/src/utils.ts
  packages/zenn-validator/tsconfig.build.json
  packages/zenn-validator/tsconfig.json
  yarn.lock
Labels: feature
