Repository zenn-dev/zenn-editor, pull requests merged in 2022-11, with the labels that each got.

#391 chore: 権限設定
  .github/workflows/policy-comment.yml
Labels: chore

#388 chore: サニタイズの注意書きを消す
  packages/zenn-cli/src/client/components/TemporarySanitizeMessageBar.tsx
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/components/chapters/show/ChapterHeader.tsx
Labels: fix

#392 YouTubeの埋め込みをプライバシー強化モードに変更
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/articles/link-card.md
  packages/zenn-cli/src/server/commands/new-article.ts
  packages/zenn-content-css/test.html
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/src/utils/embed-helper.ts
Labels: bugfix

#389 lockfile-lintの導入
  package.json
Labels: chore

#387 release v0.1.132
  .github/workflows/policy-comment.yml
  lerna.json
  package.json
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/articles/link-card.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/TemporarySanitizeMessageBar.tsx
  packages/zenn-cli/src/client/components/ValidationErrors.tsx
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-cli/src/client/components/books/show/BookHeader.tsx
  packages/zenn-cli/src/client/components/chapters/show/ChapterHeader.tsx
  packages/zenn-cli/src/server/__tests__/commands/new-article.test.ts
  packages/zenn-cli/src/server/commands/new-article.ts
  packages/zenn-content-css/package.json
  packages/zenn-content-css/test.html
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/embed-helper.ts
  packages/zenn-validator/.eslintrc.yml
  packages/zenn-validator/.gitignore
  packages/zenn-validator/README.md
  packages/zenn-validator/__tests__/validator.test.ts
  packages/zenn-validator/jest.config.js
  packages/zenn-validator/package.json
  packages/zenn-validator/src/index.ts
  packages/zenn-validator/src/types.ts
  packages/zenn-validator/src/utils.ts
  packages/zenn-validator/tsconfig.build.json
  packages/zenn-validator/tsconfig.json
  yarn.lock
Labels: release

#396 READMEを整理
  README.md
  packages/zenn-cli/README.md
  packages/zenn-content-css/README.md
  packages/zenn-embed-elements/README.md
  packages/zenn-markdown-html/README.md
  packages/zenn-validator/README.md
Labels: chore
