Repository zenn-dev/zenn-editor, pull requests merged in 2022-08, with the labels that each got.

#319 fix: error message when specifying Emoji 14
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/lib/validator.ts
  yarn.lock
Labels: chore

#320 release v0.1.116
  lerna.json
  packages/zenn-cli/books/chapter-by-config/invalid"slug.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/lib/validator.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#323 chore: コントリビューションガイドから実施不可能な項目を修正
  CONTRIBUTING.md
Labels: chore

#324 iframeのattributesを整理
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
Labels: fix

#325 埋め込みに対応する際のガイドラインを追記
  packages/zenn-markdown-html/README.md
Labels: chore

#326 fix: CodeSandBoxの埋め込みURLに`,`を含められるように修正
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: bugfix

#327 release v0.1.117
  CONTRIBUTING.md
  lerna.json
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/README.md
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: release

#330 add test for docId
  packages/zenn-markdown-html/__tests__/basic.test.ts
Labels: enhancement, chore

#333 テストエラーを修正
  packages/zenn-cli/package.json
  packages/zenn-cli/tsconfig.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: bugfix

#334 fix: zenn-cli のビルドエラーを修正
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/ErrorBoundary.tsx
  packages/zenn-cli/src/client/index.tsx
  yarn.lock
Labels: bugfix

#335 TOCプレビューのテストエラーを解消した版
  package.json
  packages/zenn-cli/articles/toc-check.md
  packages/zenn-cli/jest.config.server.js
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/Toc.tsx
  packages/zenn-cli/src/client/components/articles/show.tsx
  packages/zenn-cli/src/client/public/static-images/copy-icon.svg
  packages/zenn-cli/src/common/types.ts
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-cli/tsconfig.json
  packages/zenn-markdown-html/__tests__/toc.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/index.ts
  packages/zenn-markdown-html/src/utils/toc.ts
  yarn.lock
Labels: feature

#338 Revert "TOCプレビューのテストエラーを解消した版"
  package.json
  packages/zenn-cli/articles/toc-check.md
  packages/zenn-cli/jest.config.server.js
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/Toc.tsx
  packages/zenn-cli/src/client/components/articles/show.tsx
  packages/zenn-cli/src/client/public/static-images/copy-icon.svg
  packages/zenn-cli/src/common/types.ts
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-cli/tsconfig.json
  packages/zenn-markdown-html/__tests__/toc.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/index.ts
  packages/zenn-markdown-html/src/utils/toc.ts
  yarn.lock
Labels: feature

#340 publicaiton_name が設定されているときのみプロパティを表示するように修正
  package.json
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  yarn.lock
Labels: feature

#341 release: v0.1.118
  lerna.json
  package.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/articles/show/ArticleHeader.tsx
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/basic.test.ts
  packages/zenn-markdown-html/package.json
  yarn.lock
Labels: release

#342 アクティブな脚注がわかりやすいようにハイライト
  packages/zenn-content-css/src/_footnotes.scss
Labels: enhancement

#343 release: v0.1.119
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_footnotes.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
Labels: release
