Repository zenn-dev/zenn-editor, pull requests merged in 2023-11, with the labels that each got.

#477 package.jsonからpackageManagerの項目を削除
  package.json
Labels: chore

#478 fix: シャドウをなくす
  packages/zenn-cli/articles/toc-check.md
  packages/zenn-cli/src/client/global.css
  packages/zenn-content-css/src/_content.scss
Labels: feature

#479 release v0.1.149
  lerna.json
  package.json
  packages/zenn-cli/articles/toc-check.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/global.css
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_content.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-model/package.json
Labels: release

#480 x.comの埋め込み対応
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: feature

#481 release v0.1.150
  lerna.json
  packages/zenn-cli/articles/embed-examples.md
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/url-matcher.ts
  packages/zenn-model/package.json
Labels: release

#482 Publish workflowのnotifyをやめる
  .github/workflows/publish-latest.yml
Labels: chore
