Repository zenn-dev/zenn-editor, pull requests merged in 2023-09, with the labels that each got.

#457 feat: pnpm を v8 にアップデート
  .github/workflows/lint.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-latest.yml
  .github/workflows/test.yml
  package.json
  pnpm-lock.yaml
Labels: feature

#458 Revert "feat: pnpm を v8 にアップデート"
  .github/workflows/lint.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-latest.yml
  .github/workflows/test.yml
  package.json
  pnpm-lock.yaml
Labels: chore

#456 目次のプレビュー
  packages/zenn-cli/articles/toc-check.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/InsertAnchorButtonToHeadings.tsx
  packages/zenn-cli/src/client/components/Toc.tsx
  packages/zenn-cli/src/client/components/articles/show.tsx
  packages/zenn-cli/src/client/global.css
  packages/zenn-cli/src/client/public/static-images/copy-icon.svg
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-markdown-html/__tests__/toc.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/index.ts
  packages/zenn-markdown-html/src/utils/toc.ts
  packages/zenn-model/src/types.ts
  pnpm-lock.yaml
Labels: feature

#460 chore: pnpm v8 にアップデートし、pnpm-lock を更新
  .github/workflows/lint.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-latest.yml
  .github/workflows/test.yml
  package.json
  pnpm-lock.yaml
Labels: feature

#462 release v0.1.145
  .github/release-drafter.yml
  .github/workflows/lint.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-latest.yml
  .github/workflows/test.yml
  .github/workflows/validate-pr.yml
  lerna.json
  package.json
  packages/zenn-cli/articles/toc-check.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/InsertAnchorButtonToHeadings.tsx
  packages/zenn-cli/src/client/components/Toc.tsx
  packages/zenn-cli/src/client/components/articles/show.tsx
  packages/zenn-cli/src/client/global.css
  packages/zenn-cli/src/client/public/static-images/copy-icon.svg
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/toc.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/index.ts
  packages/zenn-markdown-html/src/utils/toc.ts
  packages/zenn-model/package.json
  packages/zenn-model/src/types.ts
  pnpm-lock.yaml
Labels: release

#463 TOCテストを日本語化
  packages/zenn-markdown-html/__tests__/toc.test.ts
Labels: chore

#464 GitHub Actions の dispatch イベントに payload を追加
  .github/workflows/publish-latest.yml
Labels: chore

#465 release v0.1.146
  .github/workflows/publish-latest.yml
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/toc.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-model/package.json
Labels: release

#466 refactor: テストのタイトルを日本語に統一
  packages/zenn-cli/src/client/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/common/__tests__/helper.test.ts
  packages/zenn-cli/src/server/__tests__/commands/help.test.ts
  packages/zenn-cli/src/server/__tests__/commands/init.test.ts
  packages/zenn-cli/src/server/__tests__/commands/new-article.test.ts
  packages/zenn-cli/src/server/__tests__/commands/new-book.test.ts
  packages/zenn-cli/src/server/__tests__/commands/preview.test.ts
  packages/zenn-cli/src/server/__tests__/commands/version.test.ts
  packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/server/__tests__/lib/log.test.ts
  packages/zenn-markdown-html/__tests__/basic.test.ts
  packages/zenn-markdown-html/__tests__/br.test.ts
  packages/zenn-markdown-html/__tests__/dollar.test.ts
  packages/zenn-markdown-html/__tests__/highlight.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-model/__tests__/validator.test.ts
Labels: chore
