Repository zenn-dev/zenn-editor, pull requests merged in 2023-02, with the labels that each got.

#421 feat: `.` から始まるファイル・ディレクトリは無視するように修正
  packages/zenn-cli/books/.ignore-book/config.yaml
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-cli/src/server/lib/books.ts
Labels: feature

#420 feat: markdownToHtml に `embedOrigin` オプションを追加した
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-cli/src/server/lib/books.ts
  packages/zenn-markdown-html/.eslintrc.yml
  packages/zenn-markdown-html/README.md
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/blueprintue.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/card.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/codepen.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/codesandbox.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/common.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/figma.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/gist.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/github.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/jsfiddle.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/mermaid.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/slideshare.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/speakerdeck.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/stackblitz.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/tweet.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/youtube.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/messagebox.test.ts
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/__tests__/mermaid.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/src/embed.ts
  packages/zenn-markdown-html/src/index.ts
  packages/zenn-markdown-html/src/types.ts
  packages/zenn-markdown-html/src/utils/embed-helper.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  packages/zenn-markdown-html/src/utils/md-linkify-to-card.ts
  packages/zenn-markdown-html/src/utils/md-renderer-fence.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
  pnpm-lock.yaml
Labels: feature

#424 feat: 全ての packages の依存関係をアップデートした
  package.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/BodyContent.tsx
  packages/zenn-cli/src/client/components/ErrorBoundary.tsx
  packages/zenn-cli/src/client/components/ErrorMessage.tsx
  packages/zenn-cli/src/client/components/Layout.tsx
  packages/zenn-cli/src/client/components/Loading.tsx
  packages/zenn-cli/src/client/components/PropertyRow.tsx
  packages/zenn-cli/src/client/components/Sidebar.tsx
  packages/zenn-cli/src/client/components/TopicList.tsx
  packages/zenn-cli/src/client/components/articles/show.tsx
  packages/zenn-cli/src/client/components/books/show/BookChapterList.tsx
  packages/zenn-cli/src/client/components/chapters/show.tsx
  packages/zenn-cli/src/client/components/home/index.tsx
  packages/zenn-cli/src/client/components/sidebar/Directory.tsx
  packages/zenn-cli/src/client/components/sidebar/ListItemInner.tsx
  packages/zenn-cli/src/client/index.tsx
  packages/zenn-cli/src/server/api/cli-guide.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-cli/vite.config.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-model/package.json
  pnpm-lock.yaml
Labels: dependencies, feature

#423 release v0.1.138
  lerna.json
  package.json
  packages/zenn-cli/books/.ignore-book/config.yaml
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/BodyContent.tsx
  packages/zenn-cli/src/client/components/ErrorBoundary.tsx
  packages/zenn-cli/src/client/components/ErrorMessage.tsx
  packages/zenn-cli/src/client/components/Layout.tsx
  packages/zenn-cli/src/client/components/Loading.tsx
  packages/zenn-cli/src/client/components/PropertyRow.tsx
  packages/zenn-cli/src/client/components/Sidebar.tsx
  packages/zenn-cli/src/client/components/TopicList.tsx
  packages/zenn-cli/src/client/components/articles/show.tsx
  packages/zenn-cli/src/client/components/books/show/BookChapterList.tsx
  packages/zenn-cli/src/client/components/chapters/show.tsx
  packages/zenn-cli/src/client/components/home/index.tsx
  packages/zenn-cli/src/client/components/sidebar/Directory.tsx
  packages/zenn-cli/src/client/components/sidebar/ListItemInner.tsx
  packages/zenn-cli/src/client/index.tsx
  packages/zenn-cli/src/server/api/cli-guide.ts
  packages/zenn-cli/src/server/lib/articles.ts
  packages/zenn-cli/src/server/lib/books.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-cli/vite.config.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/.eslintrc.yml
  packages/zenn-markdown-html/README.md
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/blueprintue.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/card.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/codepen.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/codesandbox.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/common.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/figma.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/gist.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/github.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/jsfiddle.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/mermaid.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/slideshare.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/speakerdeck.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/stackblitz.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/tweet.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/youtube.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/messagebox.test.ts
  packages/zenn-markdown-html/__tests__/custom.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/__tests__/mermaid.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/embed.ts
  packages/zenn-markdown-html/src/index.ts
  packages/zenn-markdown-html/src/types.ts
  packages/zenn-markdown-html/src/utils/embed-helper.ts
  packages/zenn-markdown-html/src/utils/md-custom-block.ts
  packages/zenn-markdown-html/src/utils/md-linkify-to-card.ts
  packages/zenn-markdown-html/src/utils/md-renderer-fence.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
  packages/zenn-model/package.json
  pnpm-lock.yaml
Labels: release

#425 fix: zenn-cli のコマンド実行時に websocket で実行時エラーが発生してしまうバグを修正
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/lib/server.ts
Labels: bugfix

#426 release v0.1.139
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/lib/server.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-model/package.json
Labels: release

#428 docs: Pull Request のテンプレートの見出しレベルを調整
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix

#427 fix: diff のコードブロックでインデントが崩れてしまう問題を修正
  packages/zenn-content-css/src/_prism.scss
Labels: bugfix

#429 release v0.1.140
  .github/PULL_REQUEST_TEMPLATE.md
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_prism.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-model/package.json
Labels: release

#431 feat: トピックにリンクを追加
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/src/client/components/TopicList.tsx
  packages/zenn-cli/src/client/global.css
Labels: feature

#435 docs: LICENSE ファイルの追加と README 内の表現を修正
  LICENSE
  README.md
  packages/zenn-cli/LICENSE
  packages/zenn-content-css/LICENSE
  packages/zenn-embed-elements/LICENSE
  packages/zenn-markdown-html/LICENSE
  packages/zenn-model/LICENSE
Labels: chore

#436 release v0.1.141
  LICENSE
  README.md
  lerna.json
  packages/zenn-cli/LICENSE
  packages/zenn-cli/articles/exampleexample.md
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/TopicList.tsx
  packages/zenn-cli/src/client/global.css
  packages/zenn-content-css/LICENSE
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/LICENSE
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/LICENSE
  packages/zenn-markdown-html/package.json
  packages/zenn-model/LICENSE
  packages/zenn-model/package.json
Labels: release
