Repository zenn-dev/zenn-editor, pull requests merged in 2023-10, with the labels that each got.

#468 feat: 各パッケージのテストを jest から vitest への移行した
  packages/zenn-cli/jest.config.client.js
  packages/zenn-cli/jest.config.server.js
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/common/__tests__/helper.test.ts
  packages/zenn-cli/src/server/__tests__/commands/help.test.ts
  packages/zenn-cli/src/server/__tests__/commands/index.test.ts
  packages/zenn-cli/src/server/__tests__/commands/init.test.ts
  packages/zenn-cli/src/server/__tests__/commands/new-article.test.ts
  packages/zenn-cli/src/server/__tests__/commands/new-book.test.ts
  packages/zenn-cli/src/server/__tests__/commands/preview.test.ts
  packages/zenn-cli/src/server/__tests__/commands/version.test.ts
  packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/server/__tests__/lib/log.test.ts
  packages/zenn-cli/src/server/__tests__/lib/notify-update.test.ts
  packages/zenn-cli/src/server/__tests__/preview/app.test.ts
  packages/zenn-cli/src/server/types.ts
  packages/zenn-cli/vitest.client.config.ts
  packages/zenn-cli/vitest.server.config.ts
  packages/zenn-markdown-html/__tests__/basic.test.ts
  packages/zenn-markdown-html/__tests__/br.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/blueprintue.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/card.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/codepen.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/codesandbox.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/common.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/figma.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/gist.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/github.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/jsfiddle.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/mermaid.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/slideshare.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/speakerdeck.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/stackblitz.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/tweet.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/youtube.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/messagebox.test.ts
  packages/zenn-markdown-html/__tests__/dollar.test.ts
  packages/zenn-markdown-html/__tests__/highlight.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/__tests__/markdown-simple-html.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isBlueprintUEUrl.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isFigmaUrl.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isGithubUrl.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isYoutubeUrl.test.ts
  packages/zenn-markdown-html/__tests__/toc.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/jest.config.js
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/vitest.config.ts
  packages/zenn-model/__tests__/validator.test.ts
  packages/zenn-model/jest.config.js
  packages/zenn-model/package.json
  packages/zenn-model/vitest.config.ts
  pnpm-lock.yaml
Labels: feature

#467 release v0.1.147
  lerna.json
  packages/zenn-cli/jest.config.client.js
  packages/zenn-cli/jest.config.server.js
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/common/__tests__/helper.test.ts
  packages/zenn-cli/src/server/__tests__/commands/help.test.ts
  packages/zenn-cli/src/server/__tests__/commands/index.test.ts
  packages/zenn-cli/src/server/__tests__/commands/init.test.ts
  packages/zenn-cli/src/server/__tests__/commands/new-article.test.ts
  packages/zenn-cli/src/server/__tests__/commands/new-book.test.ts
  packages/zenn-cli/src/server/__tests__/commands/preview.test.ts
  packages/zenn-cli/src/server/__tests__/commands/version.test.ts
  packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/server/__tests__/lib/log.test.ts
  packages/zenn-cli/src/server/__tests__/lib/notify-update.test.ts
  packages/zenn-cli/src/server/__tests__/preview/app.test.ts
  packages/zenn-cli/src/server/types.ts
  packages/zenn-cli/vitest.client.config.ts
  packages/zenn-cli/vitest.server.config.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/basic.test.ts
  packages/zenn-markdown-html/__tests__/br.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/blueprintue.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/card.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/codepen.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/codesandbox.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/common.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/figma.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/gist.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/github.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/jsfiddle.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/mermaid.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/slideshare.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/speakerdeck.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/stackblitz.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/tweet.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/embed/youtube.test.ts
  packages/zenn-markdown-html/__tests__/custom-syntax/messagebox.test.ts
  packages/zenn-markdown-html/__tests__/dollar.test.ts
  packages/zenn-markdown-html/__tests__/highlight.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/__tests__/markdown-simple-html.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isBlueprintUEUrl.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isFigmaUrl.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isGithubUrl.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isYoutubeUrl.test.ts
  packages/zenn-markdown-html/__tests__/toc.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/jest.config.js
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/vitest.config.ts
  packages/zenn-model/__tests__/validator.test.ts
  packages/zenn-model/jest.config.js
  packages/zenn-model/package.json
  packages/zenn-model/vitest.config.ts
  pnpm-lock.yaml
Labels: release

#470 コメントの修正
  packages/zenn-cli/src/client/components/InsertAnchorButtonToHeadings.tsx
Labels: chore

#472 ツールチップCSSのフォーク元を明記する
  packages/zenn-cli/src/client/global.css
Labels: chore

#473 リンクの中に画像があるとき、リンク範囲を画像の大きさに合わせる
  packages/zenn-content-css/src/_content.scss
  packages/zenn-content-css/test.html
Labels: feature

#474 release v0.1.148
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/InsertAnchorButtonToHeadings.tsx
  packages/zenn-cli/src/client/global.css
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_content.scss
  packages/zenn-content-css/test.html
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-model/package.json
Labels: release
