Repository zenn-dev/zenn-editor, pull requests merged in 2024-01, with the labels that each got.

#485 add: 角丸の定義を追加し、反映した
  packages/zenn-content-css/src/_content.scss
  packages/zenn-content-css/src/_message.scss
  packages/zenn-content-css/src/index.scss
Labels: feature

#486 Release 1.151
  .github/workflows/publish-latest.yml
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_content.scss
  packages/zenn-content-css/src/_embed.scss
  packages/zenn-content-css/src/_footnotes.scss
  packages/zenn-content-css/src/_message.scss
  packages/zenn-content-css/src/index.scss
  packages/zenn-content-css/test.html
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-model/package.json
Labels: enhancement

#488 ネストしたdetailsのスタイル崩れを修正
  packages/zenn-content-css/src/_content.scss
  packages/zenn-content-css/test.html
Labels: bug

#489 release v0.1.152
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/_content.scss
  packages/zenn-content-css/test.html
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-model/package.json
Labels: release
