Repository zenn-dev/zenn-editor, pull requests merged in 2024-02, with the labels that each got.

#491 Codesandbox URL に `+` を許容する
  packages/zenn-markdown-html/__tests__/matchers/isCodesandboxUrl.test.ts
  packages/zenn-markdown-html/src/utils/url-matcher.ts
Labels: feature

#492 release v0.1.153
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/matchers/isCodesandboxUrl.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/url-matcher.ts
  packages/zenn-model/package.json
Labels: release

#487 feat: `zenn init`で表示されるヘルプコマンドにパッケージマネージャーを使用することを明示的に追加
  packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/server/commands/init.ts
  packages/zenn-cli/src/server/lib/helper.ts
Labels: enhancement, feature
