Repository zenn-dev/zenn-editor, pull requests merged in 2024-08, with the labels that each got.

#502 fix: VSCode ESLint 設定の Deprecated 対応
  .vscode/settings.json
Labels: enhancement

#503 Prettier v3 の全面的な導入と VSCode の設定
  .prettierignore
  .vscode/extensions.json
  .vscode/settings.json
  package.json
  packages/zenn-cli/.prettierignore
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/Loading.tsx
  packages/zenn-cli/src/client/components/books/show/BookHeader.tsx
  packages/zenn-cli/src/client/index.html
  packages/zenn-cli/src/server/commands/init.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/matchers/isCodesandboxUrl.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/utils/md-link-attributes.ts
  packages/zenn-model/package.json
  pnpm-lock.yaml
  turbo.json
Labels: enhancement

#504 feat: [zenn-markdown-html] VS Code 拡張機能でのスクロール同期のためのソースマップ追加
  packages/zenn-cli/src/server/__tests__/preview/app.test.ts
  packages/zenn-markdown-html/__tests__/basic.test.ts
  packages/zenn-markdown-html/__tests__/br.test.ts
  packages/zenn-markdown-html/__tests__/dollar.test.ts
  packages/zenn-markdown-html/__tests__/highlight.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/__tests__/source-map.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/src/index.ts
  packages/zenn-markdown-html/src/sanitizer.ts
  packages/zenn-markdown-html/src/utils/md-katex.ts
  packages/zenn-markdown-html/src/utils/md-renderer-fence.ts
  packages/zenn-markdown-html/src/utils/md-source-map.ts
Labels: feature

#507 release v0.1.155
  .github/workflows/lint.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-latest.yml
  .github/workflows/test.yml
  .prettierignore
  .vscode/extensions.json
  .vscode/settings.json
  lerna.json
  package.json
  packages/zenn-cli/.prettierignore
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/Loading.tsx
  packages/zenn-cli/src/client/components/books/show/BookHeader.tsx
  packages/zenn-cli/src/client/index.html
  packages/zenn-cli/src/server/__tests__/preview/app.test.ts
  packages/zenn-cli/src/server/commands/init.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/__tests__/basic.test.ts
  packages/zenn-markdown-html/__tests__/br.test.ts
  packages/zenn-markdown-html/__tests__/dollar.test.ts
  packages/zenn-markdown-html/__tests__/highlight.test.ts
  packages/zenn-markdown-html/__tests__/link.test.ts
  packages/zenn-markdown-html/__tests__/matchers/isCodesandboxUrl.test.ts
  packages/zenn-markdown-html/__tests__/source-map.test.ts
  packages/zenn-markdown-html/__tests__/xss.test.ts
  packages/zenn-markdown-html/package.json
  packages/zenn-markdown-html/src/index.ts
  packages/zenn-markdown-html/src/sanitizer.ts
  packages/zenn-markdown-html/src/utils/md-katex.ts
  packages/zenn-markdown-html/src/utils/md-link-attributes.ts
  packages/zenn-markdown-html/src/utils/md-renderer-fence.ts
  packages/zenn-markdown-html/src/utils/md-source-map.ts
  packages/zenn-model/package.json
  pnpm-lock.yaml
  turbo.json
Labels: release

#508 CONTRIBUTING.md を削除
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: chore
