Repository zenn-dev/zenn-editor, pull requests merged in 2025-08, with the labels that each got.

#545 feat: トピック名の文字数をvalidateするように
  packages/zenn-model/__tests__/validator.test.ts
  packages/zenn-model/src/index.ts
  packages/zenn-model/src/types.ts
  packages/zenn-model/src/utils.ts
Labels: feature

#547 fix: プレビュー時に画像パスにスペース(%20)が入っていると「ファイルが存在しません」エラーが発生する
  packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/server/__tests__/preview/app.test.ts
  packages/zenn-cli/src/server/app.ts
  packages/zenn-cli/src/server/lib/helper.ts
Labels: bug

#546 release 0.2.2
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/server/__tests__/lib/helper.test.ts
  packages/zenn-cli/src/server/__tests__/preview/app.test.ts
  packages/zenn-cli/src/server/app.ts
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-model/__tests__/validator.test.ts
  packages/zenn-model/package.json
  packages/zenn-model/src/index.ts
  packages/zenn-model/src/types.ts
  packages/zenn-model/src/utils.ts
Labels: release

#548 ダークテーマのリンクテキストの色を調整
  packages/zenn-content-css/src/index.scss
Labels: chore

#549 release 0.2.3
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-content-css/src/index.scss
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-model/package.json
Labels: release
