Repository zenn-dev/zenn-editor, pull requests merged in 2025-04, with the labels that each got.

#523 TwemojiのCDNを修正
  packages/zenn-cli/src/client/components/ErrorMessage.tsx
Labels: chore

#522 feat: サーバが出した画像エラーを目立たせるようにする
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-model/package.json
  packages/zenn-model/src/index.ts
  packages/zenn-model/src/types.ts
  packages/zenn-model/src/utils.ts
  pnpm-lock.yaml
Labels: feature

#524 release 0.1.159
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-cli/src/client/components/ErrorMessage.tsx
  packages/zenn-cli/src/server/lib/helper.ts
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-model/package.json
  packages/zenn-model/src/index.ts
  packages/zenn-model/src/types.ts
  packages/zenn-model/src/utils.ts
  pnpm-lock.yaml
Labels: release

#525 feat: Node.jsセットアップアクションをv4に更新
  .github/workflows/publish-canary.yml
  .github/workflows/publish-latest.yml
Labels: dependencies

#526 release 0.1.159
  .github/workflows/publish-canary.yml
  .github/workflows/publish-latest.yml
  lerna.json
  packages/zenn-cli/package.json
  packages/zenn-content-css/package.json
  packages/zenn-embed-elements/package.json
  packages/zenn-markdown-html/package.json
  packages/zenn-model/package.json
Labels: release
